<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251205195433 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA admin');
        $this->addSql('CREATE TABLE "admin"."activity" (AC_ID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, AC_ACTIVITY VARCHAR(20) NOT NULL, AC_ACTIVITY_DESCRIPTION VARCHAR(100) DEFAULT NULL, AC_RESSOURCE_NAME VARCHAR(50) NOT NULL, AC_RESSOURCE_IDENTIFIER VARCHAR(16) DEFAULT NULL, AC_USER VARCHAR(16) NOT NULL, AC_DATE TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, AC_TRIGGERED_BY VARCHAR(16) DEFAULT NULL, PRIMARY KEY (AC_ID))');
        $this->addSql('CREATE INDEX IDX_DF0CD9CA375259F1 ON "admin"."activity" (AC_TRIGGERED_BY)');
        $this->addSql('CREATE TABLE "admin"."auth_session" (AS_ID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, AS_PHONE VARCHAR(15) NOT NULL, AS_OTP_CODE VARCHAR(4) NOT NULL, AS_CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, AS_EXPIRES_AT TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, AS_IS_VALIDATED BOOLEAN NOT NULL, PRIMARY KEY (AS_ID))');
        $this->addSql('CREATE TABLE "admin"."profile" (PR_ID VARCHAR(16) NOT NULL, PR_LABEL VARCHAR(120) NOT NULL, PR_PERSON_TYPE VARCHAR(6) NOT NULL, PR_PERMISSION TEXT NOT NULL, PR_ACTIVE BOOLEAN NOT NULL, PR_CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PR_UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (PR_ID))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROFILE_PERSON_TYPE ON "admin"."profile" (PR_PERSON_TYPE)');
        $this->addSql('CREATE TABLE "admin"."user" (US_ID VARCHAR(16) NOT NULL, US_EMAIL VARCHAR(180) DEFAULT NULL, US_ROLES JSON NOT NULL, US_PASSWORD VARCHAR(255) DEFAULT NULL, US_PHONE VARCHAR(15) DEFAULT NULL, US_DISPLAY_NAME VARCHAR(120) DEFAULT NULL, US_DELETED BOOLEAN DEFAULT false NOT NULL, US_LOCKED BOOLEAN DEFAULT false NOT NULL, US_IS_CONFIRMED BOOLEAN DEFAULT false NOT NULL, US_MUST_CHANGE_PASSWORD BOOLEAN DEFAULT false NOT NULL, US_PERSON_TYPE VARCHAR(6) NOT NULL, US_HOLDER_ID VARCHAR(16) DEFAULT NULL, US_HOLDER_TYPE VARCHAR(255) DEFAULT NULL, US_CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, US_UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, US_PROFILE VARCHAR(16) DEFAULT NULL, PRIMARY KEY (US_ID))');
        $this->addSql('CREATE INDEX IDX_69389DD6581032C8 ON "admin"."user" (US_PROFILE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_EMAIL_OWNER ON "admin"."user" (US_EMAIL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_PHONE_OWNER ON "admin"."user" (US_PHONE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_HOLDER ON "admin"."user" (US_HOLDER_ID)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE "admin"."activity" ADD CONSTRAINT FK_DF0CD9CA375259F1 FOREIGN KEY (AC_TRIGGERED_BY) REFERENCES "admin"."user" (US_ID) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "admin"."user" ADD CONSTRAINT FK_69389DD6581032C8 FOREIGN KEY (US_PROFILE) REFERENCES "admin"."profile" (PR_ID) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "admin"."activity" DROP CONSTRAINT FK_DF0CD9CA375259F1');
        $this->addSql('ALTER TABLE "admin"."user" DROP CONSTRAINT FK_69389DD6581032C8');
        $this->addSql('DROP TABLE "admin"."activity"');
        $this->addSql('DROP TABLE "admin"."auth_session"');
        $this->addSql('DROP TABLE "admin"."profile"');
        $this->addSql('DROP TABLE "admin"."user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
